openstack_availability.json
Some panels were calculating the average instead of taking the last result from tests in the current availability dashboard. This PR contains the updated version of the current availability dashboard where each panel uses the last value read rather than the average value from the last hour
=> Updated current availability panels to use last value rather than mean value

openstack_availability.json, openstack_avg_availability_over_time.json, openstack_service_graphs.json
Removed all old references to datasource `uids` and replaced with only the datasource name as a datasource will be provisioned
Dashboards Updated:
- Current Availability
- Availability over time
- OpenStack service graphs
=> Update datasource references

openstack_service_graphs.json
This dashboard also had panels moved and resized to make it clearer to read.
Additional Notes: 
Panel for Placement has been removed as there is no test for this currently. 
Have you:
Have you:
=> Add panels for Octavia, Manila, and Swift and their queries to service graph dashboard

openstack_availability.json
Added panels and queries for these three openstack components. The layout of the dashboard has also been updated as well. The uid for the dashboard has been updated so that it is clearer what the dashboard is based on its uid. Panels for Placement and the web interface have been removed as there is no test for these currently. Panels for storage and network overview have also been removed as no query had been set up for them (may be added in the future).
Have you:
Have you:
=> Add panels and queries to Current Availability Dashboard for Swift, Octavia, and Manila

openstack_avg_availability_over_time.json
Added panels and queries for these three openstack components. The layout of the dashboard has also been updated as well.
The uid for the dashboard has been updated so that it is clearer what the dashboard is based on its uid.
Panels for Placement and the web interface have been removed as there is no test for these currently.
Panels for storage and network overview have also been removed as no query had been set up for them (may be added in the future).
Have you:
Have you:
=> Updates to the average cloud availability dashboard to include panels for Octavia, Manila, and Swift

openstack_service_graphs.json
**Requires #10 to be merged first**
Updated the result breakdown panels for cinder, neutron, and nova as not all of the plots were showing on the panels.
Some of the queries returned no data and these were replaced
---
Have you:
Have you:
=> Correct results breakdown for Cinder, Neutron, and Nova in Service Graphs Dashboard

cloud_dashboard.yaml
Grafana will not trigger a refresh to load a new JSON schema into the database without this field which comes from
https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
---
Have you:
Have you:
=> Add updateIntervalSeconds to get Grafana to refresh

.github/pull_request_template.md
=> Correct personality referenced in the PR template

openstack_service_status.json
Initial addition of the service status dashboard. Hypervisor panels have been added as part of the initial creation of this dashboard.
---
Have you:
Have you:
=> Add OpenStack Service Status Dashboard

openstack_service_status.json
Blocked by #16 
---
Have you:
Have you:
=> Add CPU Panels to OpenStack Service Status Dashboard

openstack_service_status.json
=> Add memory panels to Service Status dashboard

openstack_hv_status.json, openstack_service_status_breakdown.json
Thresholds for Hypervisors if they are full, CPU full, or memory full:
- 80% and above: Red
- 50-79.9%: Amber
- Less than 50%: Green
- No data: Blue
Thresholds for number of CPUs available on a hypervisor:
- ~~20~~ 16 or more: Green
- ~~10-19~~ 9-15: Amber
- Less than ~~10~~ 8: Red
- No data: Blue
---
Have you:
Have you:
=> Add hypervisor status dashboard

openstack_service_status_breakdown.json
Updated the service status breakdown dashboard to now show the status for each component. Uses template panels to do this.
Have you:
Have you:
=> Add template panels for service status breakdown

openstack_service_graphs.json
One of the panels for swift was using a query to check for Octavia data by mistake. This has now been corrected.
Requires #21 to be merged first
Have you:
Have you:
=> Correct Swift Panel for OpenStack Services Graphs dashboard

openstack_avg_availability_over_time.json
This panel was showing True instead of 100 percent, removed the value mapping on the panel to be consistent with the rest of the dashboard panels
---
Have you:
Have you:
=> MAINT: Remove value mapping from avg availability over time on Swift

openstack_hv_overview.json
Added a new dashboard that shows the summary of the service dashboard
Have you:
Have you:
=> ENH: Add Overview dashboard for Hypervisors

openstack_gpu_pool_usage.json
Add new dashboard that shows availability across different GPU pools
---
Have you:
Have you:
=> ENH: Add dashboard for GPU pool availability

openstack_L_flavor_availability.json
Dashboard showing L flavors only
---
Have you:
Have you:
=> ENH: Add new dashboard which show the availability of l* flavors

openstack_availability.json
There was a missing character for one panel in the current availability dashboard. This caused the panel display current availability using both prod and preprod data
---
Have you:
Have you:
=> BUG: Add missing character to query for private VM creation panel

openstack_empty_dashboard.json
Empty dashboard for the openstack metrics jira task.
---
Have you:
Have you:
=> added a empty dashboard json file for openstack metrics.

Cloud Rack Average Energy Usage.json
dashboard used for monitoring cloud rack power usage
---
Have you:
Have you:
=> added a dashboard for power usage

openstack_avg_availability_over_time.json
Cloud Availability over time panel for Octavia was missing a query. The query has now been added.
Have you:
Have you:
=> BUG: Add missing query for Octavia Panel

openstack_hv_status.json
previously it was printing a metric for each HV which was quite large and caused bugs when switching between prod and dev. Made it into a table instead
=> MAINT: update hv status dashboard

Power-Metrics/cloud_power_metrics.json, Power-Metrics/cloud_rack_average_energy_usage.json
The dashboards had been saved looking at a specific date in the past where there is no data. I have changed this such that the dashboards look at the past 24 hours by default.
---
Have you:
Have you:
=> MAINT: Fixed dashboards showing no data

README.md, Weekly-Reporting/weekly-reporting.json
Added a dev / prod variable to change the dashboards based on cloud instance. 
Added more 30 day trend graphs
You can view the new dashboard changes on https://dev-grafana.nubes.rl.ac.uk and see the old dashboard on https://grafana.nubes.rl.ac.uk
---
Have you:
=> Update reporting dashboards

Slots-Available/openstack_slots_available.json
Changed the variables and queries such that when choosing "Prod" instance the prod datasource is used and when "Preprod" is chosen the dev datasource is used
---
Link to dev dashboard: https://dev-grafana.nubes.rl.ac.uk/d/slots_available/openstack-slots-available?orgId=1&from=now-1h&to=now&timezone=browser&var-Instance=CloudInfluxDB&var-Environment=openstack_grafana
Have you:
=> Change variables to allow dev influx as a source

Meerkat/cpu.json, Meerkat/ram.json, Meerkat/storage.json, Monitoring/Network_Monitoring.json
Added dashboards for Meerkat CPU, RAM, and storage. These shows the benchmarking results from meerkat hardware benchmarks.
Also added network monitoring dashboard, which shows the current network availability on the cloud.
These all pull from the MeerkatDB, which needs to be added as a new datasoruce.
Have you:
* [yes] Checked the latest commit runs on a Grafana instance using the aq personality `openstack-grafana`? 
* [yes] Dashboards have clearly labelled panels, and are easy to read?
Have you:
=> Adding meerkat dasboards

ChatOps/docker_monitoring.json, ChatOps/haproxy.json, ChatOps/node_exporter_full.json, ChatOps/service_status.json, README.md
Adding dashboards to monitor chatops status. See on [dev-grafana.nubes.rl.ac.uk](https://dev-grafana.nubes.rl.ac.uk/dashboards/f/cevnrmz9u52wwc/?orgId=1)
---
Have you:
=> ENH: Add chatops dashboards

Weekly-Reporting/weekly-reporting.json
The panels had a 30d cap set manually on the graphs. This was due to the way the data used to be sent to the datasource but has since been improved. Removing this cap allows us to see graph trends up to whatever time period the page is set to.
Dev:
https://dev-grafana.nubes.rl.ac.uk/d/aebnp23l1qhhcbdsd/weekly-reporting?orgId=1&from=now-6M&to=now&timezone=browser&var-environment=prod
Prod:
https://grafana.nubes.rl.ac.uk/d/aebnp23l1qhhcbdsd/weekly-reporting?orgId=1&from=now-1y&to=now&timezone=browser&var-environment=prod
---
Have you:
=> MAINT: Remove 30d cap from panels
